services:
    redis:
        image: redis:alpine
        container_name: redis_service
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    redisinsight:
        image: redis/redisinsight:latest
        container_name: redisinsight
        ports:
            - "5540:5540"
        depends_on:
            - redis

    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_container
        ports:
            - "8080:8080"
        depends_on:
            - redis
        volumes:
            - .:/usr/src/app

volumes:
    redis_data:
