services:
    redis:
        image: redis:alpine
        container_name: redis_service
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    redisinsight:
        image: redis/redisinsight:latest
        container_name: redisinsight
        ports:
            - "5540:5540"
        depends_on:
            - redis

    postgres:
        image: postgres:17.0-alpine3.20
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=vini
            - POSTGRES_USER=vini
            - POSTGRES_DATABASE=vini
        volumes:
            - ./tmp/data:/data

    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_container
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - postgres
        volumes:
            - .:/usr/src/app

volumes:
    redis_data:
