version: "3.8"

services:
    api:
        build:
            context: .
            dockerfile: api/Dockerfile
        container_name: api_service
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - rabbitmq

    rabbitmq:
        build:
            context: .
            dockerfile: rabbitmq/Dockerfile
        container_name: rabbimq_service
        ports:
            - "5672:5672"
            - "15672:15672"

    redis:
        image: redis:alpine
        container_name: redis_service
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
