services:
    rabbitmq:
        build:
            context: .
            dockerfile: services/rabbitmq/Dockerfile
        container_name: rabbimq_service
        ports:
            - "5672:5672"
            - "15672:15672"

    redis:
        image: redis:alpine
        container_name: redis_service
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    redisinsight:
        image: redis/redisinsight:latest
        container_name: redisinsight
        ports:
            - "5540:5540"
        depends_on:
            - redis

    api:
        build:
            context: .
            dockerfile: services/api/Dockerfile
        container_name: api_service
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - rabbitmq
        volumes:
            - ./services:api

    auth:
        build:
            context: .
            dockerfile: services/auth/Dockerfile
        container_name: auth_service
        ports:
            - "8081:8081"
        depends_on:
            - redis
            - rabbitmq
        volumes:
            - ./services:auth

volumes:
    redis_data:
